CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(200) NOT NULL,
    email VARCHAR(254),
    total_points INTEGER NOT NULL DEFAULT 0,
    display_name VARCHAR(100) NOT NULL,
    profile_bio VARCHAR(500),
    x_url VARCHAR(1000),
    stream_url VARCHAR(1000),
    profile_image_url VARCHAR(1000),
    profile_icon_color VARCHAR(7),
    profile_image_data BLOB,
    profile_image_content_type VARCHAR(100),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS friendship (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_user_id BIGINT NOT NULL,
    addressee_user_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_friendship UNIQUE (requester_user_id, addressee_user_id)
);

CREATE TABLE IF NOT EXISTS schedule_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT,
    schedule_date DATE NOT NULL,
    priority VARCHAR(10) NOT NULL DEFAULT 'LOW',
    device_type VARCHAR(30) NOT NULL DEFAULT 'PC',
    rank_band VARCHAR(100),
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    completed_at TIMESTAMP,
    message_shareable BOOLEAN NOT NULL DEFAULT FALSE,
    source_schedule_item_id BIGINT,
    source_owner_user_id BIGINT,
    title VARCHAR(200) NOT NULL,
    start_time TIME,
    end_time TIME,
    description VARCHAR(1000),
    shared_with_friends BOOLEAN NOT NULL DEFAULT FALSE,
    joinable BOOLEAN NOT NULL DEFAULT FALSE,
    recruitment_limit INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS schedule_participant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_item_id BIGINT NOT NULL,
    participant_user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_schedule_participant UNIQUE (schedule_item_id, participant_user_id)
);

CREATE TABLE IF NOT EXISTS schedule_join_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_item_id BIGINT NOT NULL,
    requester_user_id BIGINT NOT NULL,
    comment VARCHAR(500) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_schedule_join_request UNIQUE (schedule_item_id, requester_user_id)
);

CREATE TABLE IF NOT EXISTS point_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    action_type VARCHAR(50) NOT NULL,
    action_label VARCHAR(200) NOT NULL,
    points INTEGER NOT NULL,
    action_key VARCHAR(120) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_point_history_user_action_key UNIQUE (user_id, action_key)
);

CREATE TABLE IF NOT EXISTS schedule_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id BIGINT NOT NULL,
    action_type VARCHAR(30) NOT NULL,
    action_detail VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    status VARCHAR(30) NOT NULL,
    message VARCHAR(2000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS board_thread (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    game_title VARCHAR(200) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS board_post (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id BIGINT NOT NULL,
    author_user_id BIGINT NOT NULL,
    body VARCHAR(1000) NOT NULL,
    schedule_date DATE,
    start_time TIME,
    rank_band VARCHAR(100),
    recruitment_limit INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS board_post_interest (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    requester_user_id BIGINT NOT NULL,
    comment VARCHAR(500) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notification_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id BIGINT NOT NULL,
    actor_user_id BIGINT,
    event_type VARCHAR(40) NOT NULL,
    title VARCHAR(200) NOT NULL,
    body VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS push_subscription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    endpoint VARCHAR(2000) NOT NULL UNIQUE,
    p256dh VARCHAR(255) NOT NULL,
    auth VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS friend_notification_preference (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    friend_user_id BIGINT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_friend_notification_preference UNIQUE (user_id, friend_user_id)
);

CREATE TABLE IF NOT EXISTS player_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_user_id BIGINT NOT NULL,
    target_user_id BIGINT NOT NULL,
    source_type VARCHAR(40) NOT NULL,
    source_id BIGINT,
    category VARCHAR(40),
    note VARCHAR(500),
    reason VARCHAR(500) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE player_report ADD COLUMN IF NOT EXISTS category VARCHAR(40);
ALTER TABLE player_report ADD COLUMN IF NOT EXISTS note VARCHAR(500);

CREATE TABLE IF NOT EXISTS direct_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT,
    sender_user_id BIGINT NOT NULL,
    recipient_user_id BIGINT NOT NULL,
    body VARCHAR(1000) NOT NULL,
    related_schedule_item_id BIGINT,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS label_colors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    label_key VARCHAR(50) NOT NULL,
    color_hex VARCHAR(7) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_label_colors_user_key UNIQUE (user_id, label_key)
);

CREATE TABLE IF NOT EXISTS dm_conversation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_a_id BIGINT NOT NULL,
    user_b_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_dm_conversation_pair UNIQUE (user_a_id, user_b_id)
);

CREATE TABLE IF NOT EXISTS todo_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS todo_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    todo_id BIGINT NOT NULL,
    action_type VARCHAR(30) NOT NULL,
    action_detail VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE schedule_item ADD COLUMN IF NOT EXISTS owner_user_id BIGINT;
ALTER TABLE schedule_item ADD COLUMN IF NOT EXISTS priority VARCHAR(10) NOT NULL DEFAULT 'LOW';
ALTER TABLE schedule_item ADD COLUMN IF NOT EXISTS device_type VARCHAR(30) NOT NULL DEFAULT 'PC';
ALTER TABLE schedule_item ADD COLUMN IF NOT EXISTS rank_band VARCHAR(100);
ALTER TABLE schedule_item ADD COLUMN IF NOT EXISTS completed BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE schedule_item ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP;
ALTER TABLE schedule_item ADD COLUMN IF NOT EXISTS message_shareable BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE schedule_item ADD COLUMN IF NOT EXISTS source_schedule_item_id BIGINT;
ALTER TABLE schedule_item ADD COLUMN IF NOT EXISTS source_owner_user_id BIGINT;
ALTER TABLE schedule_item ADD COLUMN IF NOT EXISTS shared_with_friends BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE schedule_item ADD COLUMN IF NOT EXISTS joinable BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE schedule_item ADD COLUMN IF NOT EXISTS recruitment_limit INTEGER;
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS profile_bio VARCHAR(500);
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS x_url VARCHAR(1000);
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS stream_url VARCHAR(1000);
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS email VARCHAR(254);
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS total_points INTEGER NOT NULL DEFAULT 0;
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS profile_image_url VARCHAR(1000);
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS profile_icon_color VARCHAR(7);
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS profile_image_data BLOB;
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS profile_image_content_type VARCHAR(100);
ALTER TABLE direct_message ADD COLUMN IF NOT EXISTS conversation_id BIGINT;
ALTER TABLE board_post ADD COLUMN IF NOT EXISTS rank_band VARCHAR(100);

CREATE INDEX IF NOT EXISTS idx_user_username ON app_user(username);
CREATE UNIQUE INDEX IF NOT EXISTS uq_user_email ON app_user(email);
CREATE INDEX IF NOT EXISTS idx_friendship_requester ON friendship(requester_user_id);
CREATE INDEX IF NOT EXISTS idx_friendship_addressee ON friendship(addressee_user_id);
CREATE INDEX IF NOT EXISTS idx_schedule_owner_date ON schedule_item(owner_user_id, schedule_date);
CREATE INDEX IF NOT EXISTS idx_schedule_owner_completed ON schedule_item(owner_user_id, completed);
CREATE INDEX IF NOT EXISTS idx_schedule_source_schedule ON schedule_item(source_schedule_item_id);
CREATE INDEX IF NOT EXISTS idx_schedule_participant_schedule ON schedule_participant(schedule_item_id);
CREATE INDEX IF NOT EXISTS idx_schedule_participant_user ON schedule_participant(participant_user_id);
CREATE INDEX IF NOT EXISTS idx_schedule_join_request_schedule ON schedule_join_request(schedule_item_id, status);
CREATE INDEX IF NOT EXISTS idx_schedule_join_request_requester ON schedule_join_request(requester_user_id, status);
CREATE INDEX IF NOT EXISTS idx_point_history_user_created_at ON point_history(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_schedule_history_schedule_id ON schedule_history(schedule_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_created_at ON audit_log(created_at);
CREATE INDEX IF NOT EXISTS idx_board_thread_game_title ON board_thread(game_title);
CREATE INDEX IF NOT EXISTS idx_board_post_thread_created_at ON board_post(thread_id, created_at);
CREATE INDEX IF NOT EXISTS idx_board_post_interest_post_created_at ON board_post_interest(post_id, created_at);
CREATE INDEX IF NOT EXISTS idx_notification_event_recipient_id ON notification_event(recipient_user_id, id);
CREATE INDEX IF NOT EXISTS idx_push_subscription_user_id ON push_subscription(user_id);
CREATE INDEX IF NOT EXISTS idx_friend_notification_preference_user_id ON friend_notification_preference(user_id);
CREATE INDEX IF NOT EXISTS idx_player_report_status_created_at ON player_report(status, created_at);
CREATE INDEX IF NOT EXISTS idx_dm_recipient_created_at ON direct_message(recipient_user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_dm_sender_created_at ON direct_message(sender_user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_dm_conversation_created_at ON direct_message(conversation_id, created_at);
CREATE INDEX IF NOT EXISTS idx_dm_conversation_user_a ON dm_conversation(user_a_id);
CREATE INDEX IF NOT EXISTS idx_dm_conversation_user_b ON dm_conversation(user_b_id);
CREATE INDEX IF NOT EXISTS idx_label_colors_user_id ON label_colors(user_id);
CREATE INDEX IF NOT EXISTS idx_todo_item_created_at ON todo_item(created_at);
CREATE INDEX IF NOT EXISTS idx_todo_history_todo_id ON todo_history(todo_id);
