CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(200) NOT NULL,
    email VARCHAR(254),
    total_points INTEGER NOT NULL DEFAULT 0,
    display_name VARCHAR(100) NOT NULL,
    profile_bio VARCHAR(500),
    profile_image_url VARCHAR(1000),
    profile_icon_color VARCHAR(7),
    profile_image_data BLOB,
    profile_image_content_type VARCHAR(100),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS friendship (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_user_id BIGINT NOT NULL,
    addressee_user_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_friendship UNIQUE (requester_user_id, addressee_user_id)
);

CREATE TABLE IF NOT EXISTS schedule_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT,
    schedule_date DATE NOT NULL,
    priority VARCHAR(10) NOT NULL DEFAULT 'LOW',
    device_type VARCHAR(30) NOT NULL DEFAULT 'PC',
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    completed_at TIMESTAMP,
    message_shareable BOOLEAN NOT NULL DEFAULT FALSE,
    source_schedule_item_id BIGINT,
    source_owner_user_id BIGINT,
    title VARCHAR(200) NOT NULL,
    start_time TIME,
    end_time TIME,
    description VARCHAR(1000),
    shared_with_friends BOOLEAN NOT NULL DEFAULT FALSE,
    joinable BOOLEAN NOT NULL DEFAULT FALSE,
    recruitment_limit INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS schedule_participant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_item_id BIGINT NOT NULL,
    participant_user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_schedule_participant UNIQUE (schedule_item_id, participant_user_id)
);

CREATE TABLE IF NOT EXISTS point_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    action_type VARCHAR(50) NOT NULL,
    action_label VARCHAR(200) NOT NULL,
    points INTEGER NOT NULL,
    action_key VARCHAR(120) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_point_history_user_action_key UNIQUE (user_id, action_key)
);

CREATE TABLE IF NOT EXISTS board_thread (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    game_title VARCHAR(200) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS board_post (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id BIGINT NOT NULL,
    author_user_id BIGINT NOT NULL,
    body VARCHAR(1000) NOT NULL,
    schedule_date DATE,
    start_time TIME,
    recruitment_limit INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS direct_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_user_id BIGINT NOT NULL,
    recipient_user_id BIGINT NOT NULL,
    body VARCHAR(1000) NOT NULL,
    related_schedule_item_id BIGINT,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE schedule_item ADD COLUMN IF NOT EXISTS owner_user_id BIGINT;
ALTER TABLE schedule_item ADD COLUMN IF NOT EXISTS priority VARCHAR(10) NOT NULL DEFAULT 'LOW';
ALTER TABLE schedule_item ADD COLUMN IF NOT EXISTS device_type VARCHAR(30) NOT NULL DEFAULT 'PC';
ALTER TABLE schedule_item ADD COLUMN IF NOT EXISTS completed BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE schedule_item ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP;
ALTER TABLE schedule_item ADD COLUMN IF NOT EXISTS message_shareable BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE schedule_item ADD COLUMN IF NOT EXISTS source_schedule_item_id BIGINT;
ALTER TABLE schedule_item ADD COLUMN IF NOT EXISTS source_owner_user_id BIGINT;
ALTER TABLE schedule_item ADD COLUMN IF NOT EXISTS shared_with_friends BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE schedule_item ADD COLUMN IF NOT EXISTS joinable BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE schedule_item ADD COLUMN IF NOT EXISTS recruitment_limit INTEGER;
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS profile_bio VARCHAR(500);
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS email VARCHAR(254);
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS total_points INTEGER NOT NULL DEFAULT 0;
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS profile_image_url VARCHAR(1000);
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS profile_icon_color VARCHAR(7);
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS profile_image_data BLOB;
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS profile_image_content_type VARCHAR(100);

CREATE INDEX IF NOT EXISTS idx_user_username ON app_user(username);
CREATE UNIQUE INDEX IF NOT EXISTS uq_user_email ON app_user(email);
CREATE INDEX IF NOT EXISTS idx_friendship_requester ON friendship(requester_user_id);
CREATE INDEX IF NOT EXISTS idx_friendship_addressee ON friendship(addressee_user_id);
CREATE INDEX IF NOT EXISTS idx_schedule_owner_date ON schedule_item(owner_user_id, schedule_date);
CREATE INDEX IF NOT EXISTS idx_schedule_owner_completed ON schedule_item(owner_user_id, completed);
CREATE INDEX IF NOT EXISTS idx_schedule_source_schedule ON schedule_item(source_schedule_item_id);
CREATE INDEX IF NOT EXISTS idx_schedule_participant_schedule ON schedule_participant(schedule_item_id);
CREATE INDEX IF NOT EXISTS idx_schedule_participant_user ON schedule_participant(participant_user_id);
CREATE INDEX IF NOT EXISTS idx_point_history_user_created_at ON point_history(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_board_thread_game_title ON board_thread(game_title);
CREATE INDEX IF NOT EXISTS idx_board_post_thread_created_at ON board_post(thread_id, created_at);
CREATE INDEX IF NOT EXISTS idx_dm_recipient_created_at ON direct_message(recipient_user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_dm_sender_created_at ON direct_message(sender_user_id, created_at);
